version: '3'
services:
    frontend:
        image: frontend:0.0.1
        build: ./frontend
#        ports:
#            -   "8080:8080"
        restart: always

    backend:
        image: backend:0.0.1
        build: ./backend
#        ports:
#            -   "3000:3000"
        restart: always

    reverse-proxy:
        image: nginx:alpine
        build: ./reverse-proxy
        volumes:
            - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8111:8111"
        depends_on:
            - frontend
            - backend
        restart: always
