version: '3'
services:
    frontend:
        image: frontend:0.0.1
        build: ./frontend
        ports:
            -   "8080:8080"
        restart: always

    backend:
        image: backend:0.0.1
        build:
            context: ./backend
        ports:
            -   "3000:3000"
        restart: always

