version: '3'
services:
    frontend:
        image: frontend:0.0.1
        build: ./frontend
        depends_on:
            - reverse-proxy
        ports:
            -   "8080:8080"
        restart: always

    backend:
        image: backend:0.0.1
        build:
            context: ./backend
        depends_on:
            - reverse-proxy
        ports:
            -   "3000:3000"
        restart: always

    reverse-proxy:
        image: reverse-proxy:0.0.1
        build: ./reverse-proxy
        ports:
            - "8111:8111"
        restart: always
